/*
		program 		: 		set of instructions

		programming 	:   	art of writing program

		programmer		:		those who writes program


		computer understands 	-> 		0 & 1

		Language Translator

		compiler		:  translates a HLL source code into machine code whole at a time
		interpreter 	:  translates a HLL source code into machine code line by line
		assembler		:  translates an assembly source code into machine code



		1001 1001	->      		No Translator is Required


		ADD ax,bx    				Assembler					1001	1001
		(Assembly language)


		 High Level Language		Compiler/Interpreter		1001	1001
		 (English like Language)

		 ForTran - 	First High level language
					Formulae Translation
					used in developing scientific application

		 CoBOL - 	Common Business Oriented Language
					used in developing business application


		 C	-	  used in developing both scientific & bussiness application


		 who developed C? Dennis Ritchie


		 compiler						vs				interpreter

		 1. translates whole at a time				1. translates line by line
		 2. compiler is faster						2. interpreter is slower


*/

/* #include<stdio.h>  (header file)

main()   (minimum requirement for writing a programme)
{
printf("Welcome to C");     (printf is a library function)
} */

#include<stdio.h>
#include<conio.h>

main()		//main is user-defined function
{
	clrscr();
	printf("Welcome to My First Program");	//is a library function
}








