/*
	Operators (Predefined Symbol)

	Arithmetic Operator
	+ - / % *
	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |
	Sizeof Operator
		sizeof()


	unary
	binary
	ternery


		int 	-	int		->	int
		float  -    int		->	float
		int		-	float	->	float
		float -		float	-> float


*/

#include<conio.h>
#include<stdio.h>

main()
{
	float x;
	clrscr();
	x = 5/2;
	printf("\n%.1f",x);
	getch();
}
