/*
	Operators (Predefined Symbol)

	Arithmetic Operator
	+ - / % *
	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |
	Sizeof Operator
		sizeof()


	unary
	binary
	ternery


	typecasting : casting from one type to another


*/

#include<conio.h>
#include<stdio.h>

main()
{
	int a=5,b=2;
	float x;
	clrscr();
	x = b/a;
	printf("\n%.1f",x);
	getch();
}
