/*
	Operators (Predefined Symbol)

	Arithmetic Operator
	+ - / % *
	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |
	Sizeof Operator
		sizeof()


	unary
	binary
	ternery


*/

#include<conio.h>
#include<stdio.h>

main()
{
	int x;
	clrscr();
	x = 5 / 10 +  6.0 / 2 * 4 + 5.0 / 2 % 5;	//error
	printf("\n%d",x);
	getch();
}

//14
//2
//14
//14
//4
// 14
//25
//4
//4
//12

