/*
	Operators (Predefined Symbol)

	Arithmetic Operator
	+ - / % *
	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |
	Sizeof Operator
		sizeof()


	unary
	binary
	ternery



	/%*  1st priority	left-right

	+-    2nd priority

	x = 5 / 10 +  6.0 / 2 * 4 + 5.0 / 2 * 5;
	x = 0 +  6.0 / 2 * 4 + 5.0 / 2 * 5;
	x = 0 +  3.0 * 4 + 5.0 / 2 * 5;
	x = 0 +  12.0 + 5.0 / 2 * 5;
	x = 0 +  12.0 + 2.5 * 5;
	x = 0 +  12.0 + 12.5;
	x = 12.0 + 12.5;
	x = 24.5;
	x=24






*/

#include<conio.h>
#include<stdio.h>

main()
{
	int x;
	clrscr();
	x = 5 / 10 +  6.0 / 2 * 4 + 5.0 / 2 * 5;
	printf("\n%d",x);
	getch();
}

//24
//
//24
//
//70
//13
//10
//24
//24
//24

