/*
	Operators (Predefined Symbol)

	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |


	unary
	binary
	ternery





*/

#include<conio.h>
#include<stdio.h>

main()
{
	int x;
	int y;
	clrscr();

	//y = x = 20;

	x=20;
	y=x;


	printf("\nx = %d",x);
	printf("\ny = %d",y);

	getch();
}

