/*
	Operators (Predefined Symbol)

	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |


	unary
	binary
	ternery





*/

#include<conio.h>
#include<stdio.h>

main()
{
	int x=20;
	clrscr();

	printf("\n%d",x);

	x += 10;		//	x = x + 10

	printf("\nx = %d",x);
	getch();
}

