/*
	Operators (Predefined Symbol)

	Arithmetic Operator
	+ - / % *
	Logical Operator
	&& || !
	Conditional Operator
	?:
	Relational Operator
	< > <= >= != ==
	Assignment Opeartor
	= += -= /= etc..
	Increment/Decrement Operator
	++		--
	Bitwise Operator
	<<	>>	^	& |
	Sizeof Operator
		sizeof()





	unary
	binary
	ternery

*/

#include<conio.h>
#include<stdio.h>

main()
{
	int a=10,b=20;
	int c = a+10-b;
	clrscr();
	printf("\nC = %d",c);
	getch();
}
